set(BOOST_ROOT "C:/Users/lordjaxom/Programme/boost_1_66_0")
set(JSON_ROOT "C:/Users/lordjaxom/Programme/json-master")
set(MOSQUITTO_ROOT "C:/Users/lordjaxom/Programme/mosquitto-master")
set(UTF8_ROOT "C:/Users/lordjaxom/Programme/utf8-2.3.4")
set(WIRINGPI_ROOT "C:/Users/lordjaxom/Programme/wiringPi")
set(LIB3DPRNET_ROOT "H:/src/lib3dprnet")
set(LIB3DPRNET_BUILD_SUFFIX "-mingw")