set(BOOST_ROOT "$ENV{HOME}/src/boost_1_66_0")
set(JSON_ROOT "$ENV{HOME}/src/json-master")
set(UTF8_ROOT "$ENV{HOME}/src/utf8-2.3.4")
set(LIB3DPRNET_ROOT "$ENV{HOME}/src/lib3dprnet")
set(LIB3DPRNET_BUILD_SUFFIX "-linux")
